## Install Docker ##

- name: Install Docker
  apt: name=docker state=present

- name: add the user 'root' to 'docker' group
  user:
    name: root
    groups: docker
    append: yes

- name: chkconfig on
  service:
    name: docker
    enabled: yes
